"""Create sponsor table

Revision ID: 6b40f42fdcef
Revises: d2e1f385db2b
Create Date: 2024-07-25 19:07:02.239870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b40f42fdcef'
down_revision = 'd2e1f385db2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('brand_niche', sa.String(length=100), nullable=True),
    sa.Column('social_handles', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor')
    # ### end Alembic commands ###
